name: CI

on:
  push:
    branches: [main]

jobs:
  protect-main:
    uses: TobyAnscombe/github-actions/.github/workflows/branch-protection.yml@main
    secrets:
      token: ${{ secrets.BRANCH_PROTECTION_TOKEN }}
